# Generated by Django 5.0 on 2024-01-04 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=200)),
                ('definition', models.TextField()),
                ('actionObjectiveAbstract', models.TextField()),
                ('measuresAbstract', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LongTermGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('timeframe', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ActionObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionDefinition', models.CharField(max_length=400)),
                ('hours_per_week', models.PositiveIntegerField()),
                ('hours_per_day', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('days_per_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=9)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals_app.goal')),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='longtermGoal',
            field=models.ManyToManyField(to='goals_app.longtermgoal'),
        ),
    ]
