# Generated by Django 5.0 on 2024-01-04 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='goal',
            new_name='title',
        ),
    ]
