# Generated by Django 5.0 on 2024-01-04 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals_app', '0002_rename_goal_goal_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionobjective',
            name='days_per_week',
        ),
    ]
