# Generated by Django 5.0 on 2024-01-04 18:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals_app', '0003_remove_actionobjective_days_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermgoal',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actionobjective',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.DateField(),
        ),
    ]
