# Generated by Django 5.0 on 2024-01-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_metrics_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DayEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('level', models.CharField(choices=[('low', 'Low Energy'), ('average', 'Average Energy'), ('good', 'Good Energy'), ('high', 'High Energy')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='DrugConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('effect', models.CharField(choices=[('healthy', 'Healthy Use'), ('mixed', 'Mixed Experience'), ('toxic', 'Toxic Use')], max_length=7)),
                ('drug', models.CharField(max_length=20)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FocusLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('level', models.CharField(choices=[('distracted', 'Distracted Mind'), ('mixed', 'Mixed Mind'), ('focused', 'Focused Mind')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FreshAirExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exposure', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MorningEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('level', models.CharField(choices=[('low', 'Low Energy'), ('average', 'Average Energy'), ('good', 'Good Energy'), ('high', 'High Energy')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='MorningWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('connection', models.BooleanField()),
            ],
        ),
    ]
