# Generated by Django 5.0 on 2024-02-29 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_title', models.CharField(max_length=100)),
                ('week_description', models.CharField(max_length=200)),
                ('week_start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_block', models.CharField(choices=[('morning', 'Morning training'), ('evening', 'Evening training')], max_length=7)),
                ('event_activity', models.ManyToManyField(blank=True, to='pt_programs_app.activitytype')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100)),
                ('program_duration', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('program_details', models.TextField(blank=True)),
                ('program_notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weekly_layout', models.ManyToManyField(blank=True, to='pt_programs_app.trainingweek')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateField()),
                ('session', models.ManyToManyField(to='pt_programs_app.trainingevent')),
                ('training_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pt_programs_app.trainingweek')),
            ],
        ),
    ]
