# Generated by Django 5.0 on 2024-03-01 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_programs_app', '0001_initial'),
        ('workout_hub_app', '0003_remove_workout_training_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingday',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
        migrations.AddField(
            model_name='trainingday',
            name='session_workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_days', to='workout_hub_app.workout'),
        ),
        migrations.AlterField(
            model_name='trainingday',
            name='session',
            field=models.ManyToManyField(blank=True, to='pt_programs_app.trainingevent'),
        ),
    ]
