# Generated by Django 5.0 on 2024-03-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_programs_app', '0002_trainingday_day_of_week_trainingday_session_workout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingprogram',
            name='weekly_layout',
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='activities',
            field=models.ManyToManyField(blank=True, to='pt_programs_app.activitytype'),
        ),
    ]
