# Generated by Django 5.0 on 2024-03-04 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_programs_app', '0003_remove_trainingprogram_weekly_layout_and_more'),
        ('workout_hub_app', '0003_remove_workout_training_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitytype',
            old_name='activity',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='trainingprogram',
            old_name='activities',
            new_name='activity',
        ),
        migrations.AddField(
            model_name='trainingevent',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
        migrations.AddField(
            model_name='trainingevent',
            name='session_workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_days', to='workout_hub_app.workout'),
        ),
        migrations.AddField(
            model_name='trainingweek',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_weeks', to='pt_programs_app.trainingprogram'),
        ),
        migrations.DeleteModel(
            name='TrainingDay',
        ),
    ]
