# Generated by Django 5.0 on 2024-03-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_programs_app', '0004_rename_activity_activitytype_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingweek',
            name='week_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
